title: Juan Carlo (JC) Alicaway
description: Aspiring Data Scientist
show_downloads: false
theme: jekyll-theme-leap-day
# logo: /assets/Profile_Pic_Zoom_Png.png
# google_analytics: [Your Google Analytics tracking ID]