# Site
repository: alicaway/alicaway.github.com
favicon: images/headshot_pfp.ico

# Content configuration version
version: 2

# Personal info
name: Juan Carlo (JC) Alicaway
title: Aspiring AI/ML Engineer
email: juancarlo@alicaway.net
website: https://alicaway.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
linkedin_username: alicaway
github_username:  alicaway
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Hugging Face
  icon: fab fa-hugging-face
  url: https://huggingface.co/alicaway
- title: Kaggle
  icon: fab fa-kaggle
  url: https://www.kaggle.com/jcalicaway
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/headshot.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is JC and I am pursuing my Master of Engineering (MEng) in Artificial Intelligence (AI). \
  My experience includes Senior IT Business Analyst for the Ontario Provincial Government and Lecturer of Calculus at Ontario Tech University. \
  I am open to roles in AI Engineering, Machine Learning, or Data Science/Analytics.

  I am most skilled in: <mark>Python</mark>, <mark>Machine Learning</mark>, and <mark>Deep Learning</mark>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
